#!/usr/bin/python3
import sys
sys.setrecursionlimit(10**9)
n = int(sys.stdin.readline())
inorder = list(map(int, sys.stdin.readline().split()))
postorder = list(map(int, sys.stdin.readline().split()))

preorder = []
idx = 0
def find_preorder(ins, ine, posts, poste):
	if posts <= poste:
		root = postorder[poste]
		print(root, end=" ")
		inrootidx = root-1
		
		find_preorder(ins, inrootidx-1, posts, posts+inrootidx-1-ins)
		find_preorder(inrootidx+1, ine, poste-ine+inrootidx, poste-1)
	
find_preorder(0, len(inorder)-1, 0, len(postorder)-1)
